apiVersion: apps/v1
kind: Deployment
metadata:
  name:udhjsu
spec:
  replicas: 1
  selector:
    matchLabels:
      app:udhjsu
  template:
    metadata:
      labels:
        app:udhjsu
    spec:
      containers:
      - image: okteto.dev/udhjsu:latest
        name:udhjsu
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "b5f6edee-e82b-4cbd-aa6a-3ac79bc3cfad"
        - name: Vless_Path
          value: "/vl5e5355"
        - name: Vmess_UUID
          value: "b5f6edee-e82b-4cbd-aa6a-3ac79bc3cfad"
        - name: Vmess_Path
          value: "/vm6wts66"
        - name: Share_Path
          value: "/v2link"
