apiVersion: v1
kind: Service
metadata:
  name:udhjsu
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "udhjsu"
    port: 8080
  selector:
    app: udhjsu
